### ISSUE TITLE
error with policy: keys did not match

### ISSUE THREAD

**Issue by fansari** [jtesta/ssh-audit#130]
I wrote a policy with these host keys:

```
host keys = ssh-ed25519-cert-v01@openssh.com, ssh-ed25519
```

On the analyzed host I see:

```
sshd -T | grep hostkeyalgorithms
ssh-ed25519-cert-v01@openssh.com,ssh-ed25519
```

ssh-audit -P mypolicy.txt <hostip> shows this:

```
Result: ❌ Failed!

Errors:
  * Host keys did not match.
    - Expected: ssh-ed25519-cert-v01@openssh.com, ssh-ed25519
    - Actual:   ssh-ed25519
```

When I remove ssh-ed25519-cert-v01@openssh.com from the host keys in my policy the test passes.

Did I misconfigure something or is this a bug?
