### ISSUE TITLE
Server policies don't account for 'kex-strict-s-v00@openssh.com', yet?

### ISSUE THREAD

**Issue by mejofi** [jtesta/ssh-audit#236]
Debian just released updated packages;

https://lists.debian.org/debian-security-announce/2023/msg00283.html

When installed, the relevant server policies start failing because it now finds `kex-strict-s-v00@openssh.com` in the kex list, which does not match its expectations. This happens for both Bullseye and Bookworm, with the following server policies applied, respectively;

 * Hardened OpenSSH Server v8.4 (version 4)
 * Hardened OpenSSH Server v9.2 (version 3)

I suspect the server policy may need an update? Thanks for all the hard work and fast response, in the meantime 🙂

Example error when ran against a Debian Bullseye target;
```
Policy: Hardened OpenSSH Server v8.4 (version 4)
Result: ❌ Failed!

Errors:
  * Key exchanges did not match.
    - Expected: curve25519-sha256, curve25519-sha256@libssh.org, diffie-hellman-group16-sha512, diffie-hellman-group18-sha512, diffie-hellman-group-exchange-sha256
    - Actual:   curve25519-sha256, curve25519-sha256@libssh.org, diffie-hellman-group16-sha512, diffie-hellman-group18-sha512, diffie-hellman-group-exchange-sha256, kex-strict-s-v00@openssh.com
```
