### ISSUE TITLE
Intermittent failures when ssh-audit is run using Ansible

### ISSUE THREAD

**Issue by chriscroome** [jtesta/ssh-audit#335]
Recently, on Debian Bookworm, `ssh-audit` is failing when run against the `localhost` using Ansible, this didn't used to be the case, it is fine when run via a interactive shell, for example I'm on occasions gettig this via Ansible:

```yaml
fatal: [example.org]: FAILED! => 
    attempts: 2
    changed: false
    cmd: ssh-audit -j 127.0.0.1
    delta: '0:00:00.256544'
    end: '2025-05-30 16:23:27.215938'
    failed_when_result: true
    invocation:
        module_args:
            _raw_params: ssh-audit -j 127.0.0.1
            _uses_shell: true
            argv: null
            chdir: null
            creates: null
            executable: /usr/bin/bash
            expand_argument_vars: true
            removes: null
            stdin: null
            stdin_add_newline: true
            strip_empty_ends: true
    msg: non-zero return code
    rc: 1
    start: '2025-05-30 16:23:26.959394'
    stderr: ''
    stderr_lines: <omitted>
    stdout: |-
        {"additional_notes": [], "aut": null, "banner": {"comments": null, "protocol": null, "raw": "", "software": null}, "cves": [], "enc": null, "fingerprints": [{"fp": null, "type": "ssh-rsa1"}], "key": ["ssh-rsa1"], "recommendations": {}, "target": "127.0.0.1:22"}
        [0;31m[exception] did not receive banner.[0m
    stdout_lines: <omitted>
```

But if I `ssh` to the same server it works:

```bash
ssh-audit -j 127.0.0.1 | jq
```
```yaml
{
  "additional_notes": [
    "Be aware that, while this target properly supports the strict key exchange method (via the kex-strict-?-v00@openssh.com marker) needed to protect against the Terrapin vulnerability (CVE-2023-48795), all peers must also support this feature as well, otherwise the vulnerability will still be present.  The following algorithms would allow an unpatched peer to create vulnerable SSH channels with this target: chacha20-poly1305@openssh.com.  If any CBC ciphers are in this list, you may remove them while leaving the *-etm@openssh.com MACs in place; these MACs are fine while paired with non-CBC cipher types."
  ],
  "banner": {
    "comments": "Debian-5~bpo12+2",
    "protocol": "2.0",
    "raw": "SSH-2.0-OpenSSH_10.0p2 Debian-5~bpo12+2",
    "software": "OpenSSH_10.0p2"
  },
  "compression": [
    "none",
    "zlib@openssh.com"
  ],
  "cves": [],
  "enc": [
    {
      "algorithm": "chacha20-poly1305@openssh.com",
      "notes": {
        "info": [
          "default cipher since OpenSSH 6.9",
          "available since OpenSSH 6.5, Dropbear SSH 2020.79"
        ]
      }
    },
    {
      "algorithm": "aes256-gcm@openssh.com",
      "notes": {
        "info": [
          "available since OpenSSH 6.2"
        ]
      }
    },
    {
      "algorithm": "aes128-gcm@openssh.com",
      "notes": {
        "info": [
          "available since OpenSSH 6.2"
        ]
      }
    },
    {
      "algorithm": "aes256-ctr",
      "notes": {
        "info": [
          "available since OpenSSH 3.7, Dropbear SSH 0.52"
        ]
      }
    },
    {
      "algorithm": "aes192-ctr",
      "notes": {
        "info": [
          "available since OpenSSH 3.7"
        ]
      }
    },
    {
      "algorithm": "aes128-ctr",
      "notes": {
        "info": [
          "available since OpenSSH 3.7, Dropbear SSH 0.52"
        ]
      }
    }
  ],
  "fingerprints": [
    {
      "hash": "E3aGMSfTsJ/q37XLNJBCqxhFxdeVOiejDn60bZxZPIg",
      "hash_alg": "SHA256",
      "hostkey": "ssh-ed25519"
    },
    {
      "hash": "2e:74:f3:80:ac:fc:57:89:66:88:91:2b:f1:d1:42:92",
      "hash_alg": "MD5",
      "hostkey": "ssh-ed25519"
    },
    {
      "hash": "kGoLz6Kb6ocCcwnTqAPB0Yvi6WOLj0xBsNFNzBs/p4A",
      "hash_alg": "SHA256",
      "hostkey": "ssh-rsa"
    },
    {
      "hash": "09:fd:93:8d:8a:4f:62:c5:c5:dc:2c:cb:41:e5:c9:ed",
      "hash_alg": "MD5",
      "hostkey": "ssh-rsa"
    }
  ],
  "kex": [
    {
      "algorithm": "sntrup761x25519-sha512@openssh.com",
      "notes": {
        "info": [
          "default key exchange from OpenSSH 9.0 to 9.8",
          "hybrid key exchange based on post-quantum resistant algorithm and proven conventional X25519 algorithm",
          "available since OpenSSH 8.5"
        ]
      }
    },
    {
      "algorithm": "curve25519-sha256",
      "notes": {
        "info": [
          "default key exchange from OpenSSH 7.4 to 8.9",
          "available since OpenSSH 7.4, Dropbear SSH 2018.76"
        ]
      }
    },
    {
      "algorithm": "curve25519-sha256@libssh.org",
      "notes": {
        "info": [
          "default key exchange from OpenSSH 6.5 to 7.3",
          "available since OpenSSH 6.4, Dropbear SSH 2013.62"
        ]
      }
    },
    {
      "algorithm": "diffie-hellman-group16-sha512",
      "notes": {
        "info": [
          "available since OpenSSH 7.3, Dropbear SSH 2016.73"
        ]
      }
    },
    {
      "algorithm": "diffie-hellman-group18-sha512",
      "notes": {
        "info": [
          "available since OpenSSH 7.3"
        ]
      }
    },
    {
      "algorithm": "diffie-hellman-group-exchange-sha256",
      "keysize": 4096,
      "notes": {
        "info": [
          "available since OpenSSH 4.4"
        ]
      }
    },
    {
      "algorithm": "ext-info-s",
      "notes": {
        "info": [
          "pseudo-algorithm that denotes the peer supports RFC8308 extensions",
          "available since OpenSSH 9.6"
        ]
      }
    },
    {
      "algorithm": "kex-strict-s-v00@openssh.com",
      "notes": {
        "info": [
          "pseudo-algorithm that denotes the peer supports a stricter key exchange method as a counter-measure to the Terrapin attack (CVE-2023-48795)"
        ]
      }
    }
  ],
  "key": [
    {
      "algorithm": "rsa-sha2-512",
      "keysize": 4096,
      "notes": {
        "info": [
          "available since OpenSSH 7.2"
        ]
      }
    },
    {
      "algorithm": "rsa-sha2-256",
      "keysize": 4096,
      "notes": {
        "info": [
          "available since OpenSSH 7.2, Dropbear SSH 2020.79"
        ]
      }
    },
    {
      "algorithm": "ssh-ed25519",
      "notes": {
        "info": [
          "available since OpenSSH 6.5, Dropbear SSH 2020.79"
        ]
      }
    }
  ],
  "mac": [
    {
      "algorithm": "hmac-sha2-256-etm@openssh.com",
      "notes": {
        "info": [
          "available since OpenSSH 6.2"
        ]
      }
    },
    {
      "algorithm": "hmac-sha2-512-etm@openssh.com",
      "notes": {
        "info": [
          "available since OpenSSH 6.2"
        ]
      }
    },
    {
      "algorithm": "umac-128-etm@openssh.com",
      "notes": {
        "info": [
          "available since OpenSSH 6.2"
        ]
      }
    }
  ],
  "recommendations": {},
  "target": "127.0.0.1:22"
}
```

Has anyone else had this issue? Any ideas what the cause could be?
